version: '3'

services:

  app:
    build: app
    ports:
      - "5000:5000"
    volumes:
      - "database:/data"

  tests:
    build: .
    environment:
      FLASK_APP: app
    ports:
      - "5001:5001"
    volumes:
      - "database:/app/data"

volumes:
  database:
